(() => {
  const API = "https://api.cp6coahuila.com/api";
  const INTERNAL_SESSION = "control-avaluos.desktop.session.v1";
  const APPLICANT_SESSION = "control-avaluos.applicant";
  const esc = (value) => String(value ?? "").replace(/[&<>\"']/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;", "'":"&#39;"}[char]));
  const initials = (name) => String(name || "CP6").split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase();
  const time = (value) => value ? new Date(value).toLocaleTimeString("es-MX", { hour: "2-digit", minute: "2-digit" }) : "";
  const getIdentity = () => {
    const internal = sessionStorage.getItem(INTERNAL_SESSION);
    if (internal) return { headers: { "x-user-name": encodeURIComponent(internal) }, name: internal, kind: "internal" };
    try { const applicant = JSON.parse(sessionStorage.getItem(APPLICANT_SESSION) || "null"); if (applicant?.id || applicant?.email) return { headers: { "x-applicant-id": applicant.id || "", "x-applicant-email": applicant.email || "" }, name: applicant.name, kind: "applicant" }; } catch {}
    return null;
  };
  async function api(path, options = {}) {
    const identity = getIdentity();
    const headers = { ...(options.body instanceof FormData ? {} : { "Content-Type": "application/json" }), ...(identity?.headers || {}), ...(options.headers || {}) };
    const response = await fetch(`${API}${path}`, { ...options, headers });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(data.error || "No fue posible conectar con Mensajería.");
    return data;
  }
  let contacts = [], messages = [], activeConversation = "general", activeContact = null, timer = null, loadedIds = new Set(), externalOverlay = null;
  function viewMarkup() { return `<div class="messaging-shell"><aside class="messaging-sidebar"><div class="messaging-sidebar-head"><div class="messaging-self-avatar" id="messagingSelfAvatar">CP</div><div><strong id="messagingSelfName">Usuario CP6</strong><small id="messagingSelfEmail">Correo no registrado</small></div></div><label class="messaging-search"><input id="messagingSearch" type="search" placeholder="Buscar conversación..." autocomplete="off"></label><div id="messagingContacts" class="messaging-contacts"></div></aside><section class="messaging-conversation"><header class="messaging-conversation-head" id="messagingConversationHead"><div id="messagingContactAvatar" class="messaging-contact-avatar">CG</div><div><strong id="messagingContactName">Chat General</strong><small id="messagingContactRole">Todos los usuarios</small></div><button id="messagingInfoButton" class="messaging-info-button" type="button" aria-label="Ver información">i</button></header><div id="messagingMessages" class="messaging-messages" aria-live="polite"></div><form id="messagingForm" class="messaging-compose"><textarea id="messagingInput" rows="1" maxlength="2000" placeholder="Escribe un mensaje..." required></textarea><button type="submit" aria-label="Enviar mensaje">Enviar</button></form></section></div><div id="messagingProfileCard" class="messaging-profile-card" hidden></div>`; }
  function renderContacts() {
    const target = document.querySelector("#messagingContacts"); if (!target) return;
    const query = String(document.querySelector("#messagingSearch")?.value || "").toLocaleLowerCase("es-MX");
    const visible = contacts.filter((item) => !query || `${item.name} ${item.role} ${item.lastMessage}`.toLocaleLowerCase("es-MX").includes(query));
    target.innerHTML = visible.map((item) => `<button class="messaging-contact${item.id === activeConversation ? " is-active" : ""}" type="button" data-conversation="${esc(item.id)}"><span class="messaging-avatar">${esc(initials(item.name))}</span><span class="messaging-contact-copy"><strong>${esc(item.name)}</strong><small>${esc(item.lastMessage || item.preview || "")}</small></span><time>${esc(time(item.lastAt))}</time></button>`).join("") || `<p class="messaging-empty">No hay coincidencias.</p>`;
    target.querySelectorAll("[data-conversation]").forEach((button) => button.addEventListener("click", () => selectConversation(button.dataset.conversation)));
  }
  function renderMessages() {
    const target = document.querySelector("#messagingMessages"); if (!target) return;
    target.innerHTML = messages.length ? messages.map((item) => { const mine = item.sender_id === getIdentity()?.id || item.sender_name === getIdentity()?.name; return `<article class="messaging-message ${mine ? "is-sent" : "is-received"}"><div class="messaging-message-author">${mine ? "Tú" : esc(item.sender_name)}</div><div class="messaging-bubble">${esc(item.message).replace(/\n/g, "<br>")}</div><div class="messaging-meta">${esc(time(item.created_at))}${mine ? " · ✓✓" : ""}</div></article>`; }).join("") : `<div class="messaging-empty-state"><strong>Inicia la conversación</strong><span>Comparte información de forma segura con CP6.</span></div>`;
    target.scrollTop = target.scrollHeight;
  }
  function updateHeader() { const c = activeContact || contacts.find((item) => item.id === activeConversation) || contacts[0]; if (!c) return; activeContact = c; const avatar = document.querySelector("#messagingContactAvatar"); const name = document.querySelector("#messagingContactName"); const role = document.querySelector("#messagingContactRole"); if (avatar) avatar.textContent = initials(c.name); if (name) name.textContent = c.name; if (role) role.textContent = c.role || "Usuario CP6"; }
  async function selectConversation(id) { activeConversation = id; activeContact = contacts.find((item) => item.id === id) || null; const target = document.querySelector("#messagingMessages"); if (target) target.innerHTML = ""; renderContacts(); updateHeader(); try { messages = await api(`/messaging/messages?conversationId=${encodeURIComponent(id)}`); messages.forEach((item) => loadedIds.add(item.id)); renderMessages(); } catch (error) { if (target) target.innerHTML = `<p class="messaging-error">${esc(error.message)}</p>`; } }
  function showToast(item) { if (item.conversation_id === activeConversation && !document.querySelector(".messaging-shell")?.closest(".messaging-external-overlay")?.hidden) return; let toast = document.querySelector("#messagingToast"); if (!toast) { toast = document.createElement("div"); toast.id = "messagingToast"; toast.className = "messaging-toast"; document.body.appendChild(toast); } toast.innerHTML = `<strong>${esc(item.sender_name)}</strong><span>${esc(item.message)}</span>`; toast.onclick = () => { if (externalOverlay) selectConversation(item.conversation_id); else { document.querySelector('[data-app-view="mensajeria"]')?.click(); setTimeout(() => selectConversation(item.conversation_id), 80); } }; toast.hidden = false; clearTimeout(toast._timer); toast._timer = setTimeout(() => { toast.hidden = true; }, 7000); }
  async function pollMessages() { if (!getIdentity() || !document.querySelector(".messaging-shell")) return; try { const latest = await api(`/messaging/messages?conversationId=${encodeURIComponent(activeConversation)}`); const newItems = latest.filter((item) => !loadedIds.has(item.id)); latest.forEach((item) => loadedIds.add(item.id)); if (newItems.length && messages.length) newItems.filter((item) => item.sender_name !== getIdentity()?.name).forEach(showToast); messages = latest; renderMessages(); const data = await api("/messaging/contacts"); contacts = data.contacts || contacts; renderContacts(); } catch {} }
  async function loadMessaging(root) { const identity = getIdentity(); if (!identity) return; root.innerHTML = viewMarkup(); try { const data = await api("/messaging/contacts"); contacts = data.contacts || []; const me = data.me || identity; const self = document.querySelector("#messagingSelfAvatar"); if (self) self.textContent = initials(me.name); const selfName = document.querySelector("#messagingSelfName"); const selfEmail = document.querySelector("#messagingSelfEmail"); if (selfName) selfName.textContent = me.name || identity.name || "Usuario CP6"; if (selfEmail) selfEmail.textContent = me.email || "Correo no registrado"; renderContacts(); await selectConversation(contacts[0]?.id || "general"); document.querySelector("#messagingSearch")?.addEventListener("input", renderContacts); document.querySelector("#messagingInput")?.addEventListener("keydown", (event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); document.querySelector("#messagingForm")?.requestSubmit(); } }); document.querySelector("#messagingForm")?.addEventListener("submit", async (event) => { event.preventDefault(); const input = document.querySelector("#messagingInput"); const text = input.value.trim(); if (!text) return; input.disabled = true; try { const sent = await api("/messaging/messages", { method: "POST", body: JSON.stringify({ conversationId: activeConversation, message: text }) }); messages.push(sent); loadedIds.add(sent.id); input.value = ""; renderMessages(); const data = await api("/messaging/contacts"); contacts = data.contacts || contacts; renderContacts(); } catch (error) { window.alert(error.message); } finally { input.disabled = false; input.focus(); } }); document.querySelector("#messagingInfoButton")?.addEventListener("click", () => { const card = document.querySelector("#messagingProfileCard"); const c = activeContact || {}; card.innerHTML = `<strong>${esc(c.name || "Chat General")}</strong>${c.email ? `<span>${esc(c.email)}</span>` : ""}${c.phone ? `<small>${esc(c.phone)}</small>` : ""}`; card.hidden = !card.hidden; }); } catch (error) { root.innerHTML = `<div class="messaging-error">${esc(error.message)}</div>`; } if (timer) clearInterval(timer); timer = setInterval(pollMessages, 4000); }
  function openExternal() { if (!externalOverlay) { externalOverlay = document.createElement("div"); externalOverlay.className = "messaging-external-overlay"; externalOverlay.innerHTML = `<div class="messaging-external-window"><button class="messaging-external-close" type="button" aria-label="Cerrar">×</button><div class="messaging-external-content"></div></div>`; document.body.appendChild(externalOverlay); externalOverlay.querySelector(".messaging-external-close").addEventListener("click", () => { externalOverlay.hidden = true; }); } externalOverlay.hidden = false; loadMessaging(externalOverlay.querySelector(".messaging-external-content")); }
  function boot() { document.querySelector('[data-app-view="mensajeria"]')?.addEventListener("click", () => loadMessaging(document.querySelector("#messagingApp"))); document.querySelector("#applicantMessagingButton")?.addEventListener("click", openExternal); window.addEventListener("control-avaluos:authenticated", () => { document.querySelector('[data-app-view="mensajeria"]')?.classList.remove("is-hidden"); }); }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot); else boot();
})();
