(() => {
  const API = "https://api.cp6coahuila.com/api";
  const INTERNAL_SESSION = "control-avaluos.desktop.session.v1";
  const APPLICANT_SESSION = "control-avaluos.applicant";
  const esc = (value) => String(value ?? "").replace(/[&<>\"']/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;", "'":"&#39;"}[char]));
  const firstName = (name) => String(name || "Usuario").trim().split(/\s+/)[0] || "Usuario";
  const initials = (name) => String(name || "CP6").split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase();
  const time = (value) => value ? new Date(value).toLocaleTimeString("es-MX", { hour: "2-digit", minute: "2-digit" }) : "";
  const getIdentity = () => {
    const internal = sessionStorage.getItem(INTERNAL_SESSION);
    if (internal) return { headers: { "x-user-name": encodeURIComponent(internal) }, name: firstName(internal), fullName: internal, kind: "internal" };
    try { const applicant = JSON.parse(sessionStorage.getItem(APPLICANT_SESSION) || "null"); if (applicant?.id || applicant?.email) return { headers: { "x-applicant-id": applicant.id || "", "x-applicant-email": applicant.email || "" }, name: applicant.name, kind: "applicant" }; } catch {}
    return null;
  };
  async function api(path, options = {}) {
    const identity = getIdentity();
    const headers = { ...(options.body instanceof FormData ? {} : { "Content-Type": "application/json" }), ...(identity?.headers || {}), ...(options.headers || {}) };
    const response = await fetch(`${API}${path}`, { ...options, headers });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(data.error || "No fue posible conectar con Mensajería.");
    return data;
  }
  let contacts = [], messages = [], activeConversation = "general", activeContact = null, timer = null, loadedIds = new Set();
  function viewMarkup() { return `<div class="messaging-shell"><aside class="messaging-sidebar"><div class="messaging-sidebar-head"><div class="messaging-self-avatar" id="messagingSelfAvatar">CP</div><div><strong id="messagingSelfName">Usuario CP6</strong><small id="messagingSelfEmail">Correo no registrado</small></div></div><div class="messaging-search-row"><label class="messaging-search"><input id="messagingSearch" type="search" placeholder="Buscar conversación..." autocomplete="off"></label><button id="messagingAddContact" class="messaging-add-contact" type="button" title="Buscar y agregar contacto">+</button></div><div id="messagingInviteResults" class="messaging-invite-results" hidden></div><div id="messagingPendingInvites" class="messaging-pending-invites" hidden></div><div id="messagingContacts" class="messaging-contacts"></div></aside><section class="messaging-conversation"><header class="messaging-conversation-head" id="messagingConversationHead"><div id="messagingContactAvatar" class="messaging-contact-avatar">CG</div><div><strong id="messagingContactName">Chat General</strong><small id="messagingContactRole">Todos los usuarios</small></div><button id="messagingInfoButton" class="messaging-info-button" type="button" aria-label="Ver información">i</button></header><div id="messagingMessages" class="messaging-messages" aria-live="polite"></div><form id="messagingForm" class="messaging-compose"><textarea id="messagingInput" rows="1" maxlength="2000" placeholder="Escribe un mensaje..." required></textarea><button type="submit" aria-label="Enviar mensaje">Enviar</button></form></section></div><div id="messagingProfileCard" class="messaging-profile-card" hidden></div>`; }
  function renderContacts() {
    const target = document.querySelector("#messagingContacts"); if (!target) return;
    const query = String(document.querySelector("#messagingSearch")?.value || "").toLocaleLowerCase("es-MX");
    const visible = contacts.filter((item) => !query || `${item.name} ${item.role} ${item.lastMessage}`.toLocaleLowerCase("es-MX").includes(query));
    target.innerHTML = visible.map((item) => `<button class="messaging-contact${item.id === activeConversation ? " is-active" : ""}" type="button" data-conversation="${esc(item.id)}"><span class="messaging-avatar">${esc(initials(item.name))}</span><span class="messaging-contact-copy"><strong>${esc(item.name)}</strong><small>${esc(item.lastMessage || item.preview || "")}</small></span><time>${esc(time(item.lastAt))}</time></button>`).join("") || `<p class="messaging-empty">No hay coincidencias.</p>`;
    target.querySelectorAll("[data-conversation]").forEach((button) => button.addEventListener("click", () => selectConversation(button.dataset.conversation)));
  }
  function renderMessages() {
    const target = document.querySelector("#messagingMessages"); if (!target) return;
    target.innerHTML = messages.length ? messages.map((item) => { const mine = item.sender_id === getIdentity()?.id || item.sender_name === getIdentity()?.name; return `<article class="messaging-message ${mine ? "is-sent" : "is-received"}"><div class="messaging-message-author">${mine ? "Tú" : esc(firstName(item.sender_name))}</div><div class="messaging-bubble">${esc(item.message).replace(/\n/g, "<br>")}</div><div class="messaging-meta">${esc(time(item.created_at))}${mine ? " · ✓✓" : ""}</div></article>`; }).join("") : `<div class="messaging-empty-state"><strong>Inicia la conversación</strong><span>Comparte información de forma segura con CP6.</span></div>`;
    target.scrollTop = target.scrollHeight;
  }
  function updateHeader() { const c = activeContact || contacts.find((item) => item.id === activeConversation) || contacts[0]; if (!c) return; activeContact = c; const avatar = document.querySelector("#messagingContactAvatar"); const name = document.querySelector("#messagingContactName"); const role = document.querySelector("#messagingContactRole"); if (avatar) avatar.textContent = initials(c.name); if (name) name.textContent = c.name; if (role) role.textContent = c.role || "Usuario CP6"; }
  async function selectConversation(id) { activeConversation = id; activeContact = contacts.find((item) => item.id === id) || null; const target = document.querySelector("#messagingMessages"); if (target) target.innerHTML = ""; renderContacts(); updateHeader(); try { messages = await api(`/messaging/messages?conversationId=${encodeURIComponent(id)}`); messages.forEach((item) => loadedIds.add(item.id)); renderMessages(); } catch (error) { if (target) target.innerHTML = `<p class="messaging-error">${esc(error.message)}</p>`; } }
  function showToast(item) { if (item.conversation_id === activeConversation && !document.querySelector(".messaging-shell")?.closest(".messaging-external-overlay")?.hidden) return; let toast = document.querySelector("#messagingToast"); if (!toast) { toast = document.createElement("div"); toast.id = "messagingToast"; toast.className = "messaging-toast"; document.body.appendChild(toast); } toast.innerHTML = `<strong>${esc(item.sender_name)}</strong><span>${esc(item.message)}</span>`; toast.onclick = () => { document.querySelector('[data-app-view="mensajeria"]')?.click(); setTimeout(() => selectConversation(item.conversation_id), 80); }; toast.hidden = false; clearTimeout(toast._timer); toast._timer = setTimeout(() => { toast.hidden = true; }, 7000); }
  async function pollMessages() { if (!getIdentity() || !document.querySelector(".messaging-shell")) return; try { const latest = await api(`/messaging/messages?conversationId=${encodeURIComponent(activeConversation)}`); const newItems = latest.filter((item) => !loadedIds.has(item.id)); latest.forEach((item) => loadedIds.add(item.id)); if (newItems.length && messages.length) newItems.filter((item) => item.sender_name !== getIdentity()?.name).forEach(showToast); messages = latest; renderMessages(); const data = await api("/messaging/contacts"); contacts = data.contacts || contacts; renderContacts(); } catch {} }
  async function loadInvites() { const box = document.querySelector("#messagingPendingInvites"); if (!box) return; try { const data = await api("/messaging/invites"); const invites = data || []; box.innerHTML = invites.length ? `<strong>Invitaciones pendientes</strong>${invites.map((item) => `<div><span>${esc(firstName(item.sender?.name || "Usuario"))} quiere agregarte</span><button type="button" data-accept-invite="${esc(item.id)}">Aceptar</button></div>`).join("")}` : ""; box.hidden = !invites.length; box.querySelectorAll("[data-accept-invite]").forEach((button) => button.addEventListener("click", async () => { try { await api(`/messaging/invites/${encodeURIComponent(button.dataset.acceptInvite)}/accept`, { method: "POST" }); await loadInvites(); const refreshed = await api("/messaging/contacts"); contacts = refreshed.contacts || contacts; renderContacts(); } catch (error) { window.alert(error.message); } })); } catch { box.hidden = true; } }
  async function searchAndInvite(query) { const box = document.querySelector("#messagingInviteResults"); if (!box || !query.trim()) { if (box) box.hidden = true; return; } try { const data = await api(`/messaging/search?q=${encodeURIComponent(query.trim())}`); box.innerHTML = (data.results || []).map((item) => `<button type="button" data-invite-id="${esc(item.id)}" data-invite-kind="${esc(item.kind)}"><strong>${esc(firstName(item.name))}</strong><small>${esc(item.email || item.phone || item.role || "")}</small><span>${item.alreadyContact ? "Agregado" : "Invitar"}</span></button>`).join("") || `<p>No se encontró ningún usuario.</p>`; box.hidden = false; box.querySelectorAll("[data-invite-id]").forEach((button) => button.addEventListener("click", async () => { if (button.querySelector("span")?.textContent === "Agregado") return; try { await api("/messaging/invites", { method: "POST", body: JSON.stringify({ recipientId: button.dataset.inviteId, recipientKind: button.dataset.inviteKind }) }); button.querySelector("span").textContent = "Invitación enviada"; } catch (error) { window.alert(error.message); } })); } catch (error) { box.innerHTML = `<p>${esc(error.message)}</p>`; box.hidden = false; } }
  async function loadMessaging(root) { const identity = getIdentity(); if (!identity) return; root.innerHTML = viewMarkup(); try { const data = await api("/messaging/contacts"); contacts = data.contacts || []; await loadInvites(); const me = data.me || identity; const self = document.querySelector("#messagingSelfAvatar"); if (self) self.textContent = initials(me.name); const selfName = document.querySelector("#messagingSelfName"); const selfEmail = document.querySelector("#messagingSelfEmail"); if (selfName) selfName.textContent = firstName(me.name || identity.name) || "Usuario CP6"; if (selfEmail) selfEmail.textContent = me.email || "Correo no registrado"; renderContacts(); await selectConversation(contacts[0]?.id || "general"); document.querySelector("#messagingSearch")?.addEventListener("input", (event) => { renderContacts(); searchAndInvite(event.target.value); }); document.querySelector("#messagingInput")?.addEventListener("keydown", (event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); document.querySelector("#messagingForm")?.requestSubmit(); } }); document.querySelector("#messagingAddContact")?.addEventListener("click", () => document.querySelector("#messagingSearch")?.focus()); document.querySelector("#messagingForm")?.addEventListener("submit", async (event) => { event.preventDefault(); const input = document.querySelector("#messagingInput"); const text = input.value.trim(); if (!text) return; input.disabled = true; try { const sent = await api("/messaging/messages", { method: "POST", body: JSON.stringify({ conversationId: activeConversation, message: text }) }); messages.push(sent); loadedIds.add(sent.id); input.value = ""; renderMessages(); const refreshed = await api("/messaging/contacts"); contacts = refreshed.contacts || contacts; renderContacts(); } catch (error) { window.alert(error.message); } finally { input.disabled = false; input.focus(); } }); document.querySelector("#messagingInfoButton")?.addEventListener("click", () => { const card = document.querySelector("#messagingProfileCard"); const c = activeContact || {}; card.innerHTML = `<strong>${esc(c.fullName || c.name || "Chat General")}</strong>${c.email ? `<span>${esc(c.email)}</span>` : ""}${c.phone ? `<small>${esc(c.phone)}</small>` : ""}`; card.hidden = !card.hidden; }); } catch (error) { root.innerHTML = `<div class="messaging-error">${esc(error.message)}</div>`; } if (timer) clearInterval(timer); timer = setInterval(pollMessages, 4000); }

  function openExternal() { const section = document.querySelector("#applicantMessagingView"); const root = document.querySelector("#applicantMessagingApp"); if (!section || !root) return; section.hidden = false; document.querySelector(".client-history-section")?.setAttribute("hidden", "hidden"); loadMessaging(root); section.scrollIntoView({ behavior: "smooth", block: "start" }); }
  function boot() { document.querySelectorAll('[data-app-view="mensajeria"]').forEach((button) => button.addEventListener("click", () => loadMessaging(document.querySelector("#messagingApp")))); document.querySelector("#applicantMessagingButton")?.addEventListener("click", openExternal); document.querySelector("#applicantMessagingBackButton")?.addEventListener("click", () => { document.querySelector("#applicantMessagingView").hidden = true; document.querySelector(".client-history-section")?.removeAttribute("hidden"); }); window.addEventListener("control-avaluos:authenticated", () => { document.querySelector('[data-app-view="mensajeria"]')?.classList.remove("is-hidden"); }); }

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot); else boot();
})();
